files:
  include: 'app/assets/styles/**/*.s+(a|c)ss'
  ignore:
    - 'app/assets/styles/vendors/**/*.*'
    - 'app/assets/styles/base/_print.scss'
rules:
  # Line Spacing
  single-line-per-selector: 0

  # Disallows
  no-color-literals: 0
  no-css-comments: 0
  no-duplicate-properties: 0
  no-empty-rulesets: 0
  no-misspelled-properties: 0
  no-qualifying-elements: 0
  no-vendor-prefixes: 0

  # Nesting
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format: 0

  # Style Guide
  clean-import-paths: 0
  indentation: 0
  property-sort-order: 0
  quotes: 0

  mixins-before-declarations: 0
